"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class value_t(object):
    __slots__ = ["speed", "rpm"]

    def __init__(self):
        self.speed = ""
        self.rpm = ""

    def encode(self):
        buf = BytesIO()
        buf.write(value_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __speed_encoded = self.speed.encode('utf-8')
        buf.write(struct.pack('>I', len(__speed_encoded)+1))
        buf.write(__speed_encoded)
        buf.write(b"\0")
        __rpm_encoded = self.rpm.encode('utf-8')
        buf.write(struct.pack('>I', len(__rpm_encoded)+1))
        buf.write(__rpm_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != value_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return value_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = value_t()
        __speed_len = struct.unpack('>I', buf.read(4))[0]
        self.speed = buf.read(__speed_len)[:-1].decode('utf-8', 'replace')
        __rpm_len = struct.unpack('>I', buf.read(4))[0]
        self.rpm = buf.read(__rpm_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if value_t in parents: return 0
        tmphash = (0x9ae67fc0a139883f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if value_t._packed_fingerprint is None:
            value_t._packed_fingerprint = struct.pack(">Q", value_t._get_hash_recursive([]))
        return value_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

